theme: minima

title: "Arycama's Blog"
author: "Arycama"
description: "Game Dev, Graphics Programming and Shaders" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
twitter_username: "bensimstech"
github_username: "arycama"
linkedin_username: "arycama"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

# Used by simple links page
social-links:
  LinkedIn:        https://linkedin.com/in/arycama
  GitHub:          https://github.com/arycama
  Twitter:         https://twitter.com/bensimstech
  Reddit:          https://reddit.com/user/arycama
  Website:         /

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

collections:
  personal: # collection for personal blog posts
    output: true

header_pages:
  - archive.md
  - projects.md

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
